[package]
name = "csa"
version = "1.0.2"
authors = ["nozaq"]
description = "A Shogi game serialization/deserialization library in CSA format."
keywords = ["shogi", "csa", "parser"]
categories = ["game-engines"]
repository = "https://github.com/Arborescent/shogi-kifu-rs"
documentation = "http://nozaq.github.io/csa-rs"
readme = "README.md"
license = "MIT"
edition = "2021"

[dependencies]
time = { version = "0.3", features = ["formatting", "std"] }
pest = "2"
pest_derive = "2"

[badges]
travis-ci = { repository = "nozaq/csa-rs" }
appveyor = { repository = "nozaq/csa-rs" }
